Repository QLNU-Sec-Team/QLNU-Sec-Team.github.io, pull requests merged in 2024-08, with the labels that each got.

#7 feat: add pr template and release-drafter
  .github/pull-request-template.md
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: documentation, enhancement

#8 Fix: yaml invalid and PR template name wrong
  .github/pull_request_template.md
  .github/release-drafter.yml
Labels: bug

#9 docs: readme completed
  .github/workflows/readme-contributors.yml
  README.md
  package.json
  src/pages/components/Footer.astro
  src/pages/layouts/BaseLayout.astro
  src/pages/layouts/BaseMarkdownLayout.astro
  src/pages/member.astro
Labels: documentation, feature

#13 Update award.md
  src/pages/award.md
Labels: documentation

#10 docs: Correct punctuation placement and improve coherence of some sentences in the index page.
  src/pages/index.md
Labels: documentation

#16 add awards
  src/pages/award.md
Labels: documentation

#17 fix some errors
  README.md
  src/pages/award.md
  src/pages/index.md
Labels: bug

#18 categorized awars by year and compressed image
  public/QLNU.png
  public/award_1.jpg
  public/icon.png
  src/pages/award.md
Labels: documentation, feature

#19 修改布局，修改css，修改部分信息
  astro.config.mjs
  package-lock.json
  src/assets/memberList.json
  src/pages/award.md
  src/pages/components/Footer.astro
  src/pages/components/NavItem.astro
  src/pages/components/Navbar.astro
  src/pages/index.md
  src/pages/layouts/BaseLayout.astro
  src/pages/layouts/BaseMarkdownLayout.astro
  src/pages/member.astro
Labels: feature
